USE [master]
GO

/****** Object:  Database [TodoApp]    Script Date: 12/12/2019 16:09:17 ******/
CREATE DATABASE [TodoApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TodoApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TodoApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TodoApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\TodoApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TodoApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TodoApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TodoApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TodoApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TodoApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [TodoApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TodoApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TodoApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TodoApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TodoApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TodoApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TodoApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TodoApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TodoApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TodoApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TodoApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TodoApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TodoApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TodoApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TodoApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TodoApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TodoApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TodoApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TodoApp] SET  MULTI_USER 
GO

ALTER DATABASE [TodoApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TodoApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TodoApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TodoApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TodoApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TodoApp] SET QUERY_STORE = OFF
GO

USE [TodoApp]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TodoApp] SET  READ_WRITE 
GO


USE [TodoApp]
GO
/****** Object:  Table [dbo].[Todoes]    Script Date: 12/12/2019 16:11:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Todoes](
	[TodoId] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](500) NULL,
	[Estatus] [nvarchar](50) NULL,
	[Documento] [nvarchar](200) NULL,
 CONSTRAINT [PK_TODO] PRIMARY KEY CLUSTERED 
(
	[TodoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
